### ISSUE TITLE
`mj init`

### ISSUE THREAD

**Issue by imlucas** [mongodb-js/mj#3]
For someone who is just starting to work on mongodb-js, they should be able to just `npm install -g mj && mj init` to install and do initial configuration of things like:
- [ ] ~~prompt for name, email~~ this is not necessary at this point.
- [ ] ~~installs/updates all khaos templates~~ they now come shipped with `mj`, see #2 and #4
- [x] set sublime text config to hide all dot files (.travis, .jshintrc) so things
  that shouldn't be edited aren't
- [x] install/configure sublime text plugins

**Comment by rueckstiess** [comment]
Not everyone on sublime though. How about:

```
Usage: 
  mj init [--sublime] [-h]

Options:
  --sublime        Installs sublime plugins (JSFMT, JSHint Gutter) if not present, hides dot files
```

>  installs/updates all khaos templates

Which templates are these?

**Comment by rueckstiess** [comment]
Propose to rename `init` to `install`. Init sounds so harmless, and is probably better used to "initialize" a repo (i.e. add missing files, or register it with mongodb-js mothership). 

`mj install` does what is says: it installs stuff (independent of current repo).

The first two items (prompt for name, install templates) should be moved to `mj create`.

**Comment by rueckstiess** [comment]
Sublime Data directory:

https://sublime-text-unofficial-documentation.readthedocs.org/en/latest/basic_concepts.html?highlight=config#the-data-directory

**Comment by rueckstiess** [comment]
If Package Control is installed in Sublime, packages can be "registered" by simply adding them to `Package Control.sublime-settings`. On next restart of sublime they will be installed. 

This is probably the easiest and "gentlest" way to get plugins installed.
